/**
 * Hippocampus (Tier 2) – Two-pass inference pipeline.
 *
 * Intercepts the user prompt before it reaches the large frontier model (Tier 3).
 * Sends the prompt to a local Tiny LLM (Ollama) with the "Librarian" system prompt
 * to synthesise a context "Briefing" from the Zettelkasten.
 * The Briefing is then prepended to the user prompt for the Tier 3 model.
 *
 * Circuit-breaker: if Ollama is unreachable or too slow the briefing phase is
 * silently skipped so the system degrades gracefully.
 */

import type { EideticConfig } from "./config.js";
import { DEFAULT_HIPPO_MODEL, DEFAULT_OLLAMA_BASE_URL, LIBRARIAN_SYSTEM_PROMPT } from "./config.js";

// ============================================================================
// Types
// ============================================================================

/** Minimal subset of an Ollama /api/chat response that we parse. */
type OllamaChatResponse = {
  message?: { content?: string };
  done?: boolean;
};

// ============================================================================
// Hippocampus
// ============================================================================

export class Hippocampus {
  private readonly baseUrl: string;
  private readonly model: string;

  constructor(cfg: EideticConfig = {}) {
    this.baseUrl = (cfg.ollamaBaseUrl ?? DEFAULT_OLLAMA_BASE_URL).replace(/\/$/, "");
    this.model = cfg.hippoModel ?? DEFAULT_HIPPO_MODEL;
  }

  /**
   * Query the Tiny LLM with the user prompt and return the Librarian Briefing.
   *
   * @param userPrompt  The raw user message.
   * @param timeoutMs   Hard timeout (default: 8 000 ms to stay within the <2 s
   *                    latency target for consumer hardware).
   * @returns           The briefing text, or null if the call failed / timed out.
   */
  async fetchBriefing(userPrompt: string, timeoutMs = 8_000): Promise<string | null> {
    const url = `${this.baseUrl}/api/chat`;
    const body = JSON.stringify({
      model: this.model,
      stream: false,
      messages: [
        { role: "system", content: LIBRARIAN_SYSTEM_PROMPT },
        { role: "user", content: userPrompt },
      ],
    });

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body,
        signal: controller.signal,
      });
      if (!res.ok) {
        return null;
      }
      const json = (await res.json()) as OllamaChatResponse;
      const content = json.message?.content?.trim() ?? "";
      return content || null;
    } catch {
      // Network error or timeout – degrade gracefully
      return null;
    } finally {
      clearTimeout(timer);
    }
  }

  /**
   * Build the enriched context string to prepend to the main LLM prompt.
   * Returns empty string when no briefing could be obtained.
   */
  async buildContextBlock(userPrompt: string, timeoutMs?: number): Promise<string> {
    const briefing = await this.fetchBriefing(userPrompt, timeoutMs);
    if (!briefing) {
      return "";
    }
    return [
      "<!-- Eidetic Zettelkasten Context (generated by Hippocampus) -->",
      briefing,
      "<!-- End Eidetic Context -->",
      "",
    ].join("\n");
  }
}
